### ISSUE TITLE
Erro ao tentar instalar pacote: [dcc32 Error] Horse.Boss.Initializer.pas(103): E2010 Incompatible types: 'TNewLineEvent' and 'Procedure'

### ISSUE THREAD

**Issue by lidernetworktecnologia** [HashLoad/horse-wizard#10]
Nao consigo instalar o dpk devido ao erro de compilaçao para Alexandria 11.3:

[dcc32 Error] Horse.Boss.Initializer.pas(103): E2010 Incompatible types: 'TNewLineEvent' and 'Procedure'

**Comment by Ruda-Mu** [comment]
I had the same problem. I fixed it with me, but I don't know if and how to record it here.

**Comment by viniciussanchez** [comment]
Were you able to resolve it? There must be some incompatibility with the Delphi version.

**Comment by alanlucasjss** [comment]
Estou com o mesmo problema no  Delphi 10.3 Version 26.0.36039.7899 
[dcc32 Error] Horse.Boss.Initializer.pas(103): E2010 Incompatible types: 'TNewLineEvent' and 'Procedure'

**Comment by alanlucasjss** [comment]
@viniciussanchez 
Tive o mesmo problema no Delphi 10.3 Version 26.0.36039.7899
[dcc32 Error] Horse.Boss.Initializer.pas(103): E2010 Incompatible types: 'TNewLineEvent' and 'Procedure'
[dcc32 Error] Horse.Boss.Initializer.pas(114): E2250 There is no overloaded version of 'Queue' that can be called with these arguments
[dcc32 Fatal Error] horse_wizard.dpk(44): F2063 Could not compile used unit 'Horse.Boss.Initializer.pas'


Segue a correção que eu fiz
[Horse.Boss.Initializer.zip](https://github.com/HashLoad/horse-wizard/files/14234567/Horse.Boss.Initializer.zip)

Segue também uma alteração no template que não tem relação com o erro, mas ao gerar um novo projeto console nesse ultima versão do horse não compilava
[Horse.NewProject.Templates.zip](https://github.com/HashLoad/horse-wizard/files/14234720/Horse.NewProject.Templates.zip)

**Comment by viniciussanchez** [comment]
@alanlucasjss você não quer enviar um pull request com a correção? Assim você fica como colaborador do projeto... e facilita também para mim saber o que de fato eu teria que ajustar... se possível é claro... desde já obrigado pela colaboração.
