### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by acarlomagno** [HashLoad/horse-wizard#8]
Hello, 
I am trying horse-wizard ... but when i save the project it fails to execute boss and i get this error (does not find the specified file)
i tried to launch boss from any folder and it works.

see here https://imgur.com/a/fO6RdEW

Why?
thanks

**Comment by viniciussanchez** [comment]
![image](https://user-images.githubusercontent.com/16382981/173813584-cc3237ff-16b0-402b-beb5-fa5b6b714f95.png)

**Comment by acarlomagno** [comment]
[RESOLVE] there was an error in the BOSS installation ... now everything works.
