### ISSUE TITLE
 Required package 'DOSCommandDD' not found

### ISSUE THREAD

**Issue by TeoWin** [HashLoad/horse-wizard#9]
[dcc32 Fatal Error] horse_wizard.dpk(40): E2202 Required package 'DOSCommandDD' not found when opening and compiling the package.

Funny.. I got the same error when installing Boss. Was that not the package and dependency manager?

**Comment by viniciussanchez** [comment]
How are you going to install it?

**Comment by TeoWin** [comment]
I guess not at all.  [edited] A horse download is optional, I removed the unit and the code. [/edited]

[dcc32 Error] Horse.Boss.Initializer.pas(103): E2010 Incompatible types: 'TNewLineEvent' and 'Procedure'
[dcc32 Error] Horse.Boss.Initializer.pas(114): E2250 There is no overloaded version of 'Queue' that can be called with these arguments
[dcc32 Fatal Error] horse_wizard.dpk(44): F2063 Could not compile used unit 'Horse.Boss.Initializer.pas'

These files are from the master branch. Downloaded them today.

**Comment by pmeder** [comment]
Any Updates on that? Get the same error trying to generate the package.

**Comment by TeoWin** [comment]
@pmeder to help you out: DOSCommandDD is in https://github.com/TurboPack/DOSCommand. I guess I installed it because I got Horse working. I have not seen any follow-up on this issue in the past months. I think you saw my initial comment. I closed this issue, don't know if it is fixed or not.
